### ISSUE TITLE
Double click does not work with Firefox / Marionette

### ISSUE THREAD

**Issue by bhecquet** [bhecquet/seleniumRobot#77]
Due to https://github.com/mozilla/geckodriver/issues/661
This is corrected in Firefox 59 but we cannot wait until that version 

See workaround 

`private void doubleClickWithJavascript(WebElement element) {
    String jsCode = "var evObj = new MouseEvent('dblclick', {bubbles: true, cancelable: true, view: window});";
    jsCode += " arguments[0].dispatchEvent(evObj);";
    driver.executeScript(jsCode, element);
}`

workaround should be possible on a per-method / per browser version basis
- get driver version from capabilities
- create a workaround object which defines methods that could be rewritten spcifically for a browser version
In `HTMLElement`class, add a IF when some workaround has to be added (e.g: call javascript instead of native call)

**Comment by bhecquet** [comment]
Thanks for the tip

**Comment by claudia1204** [comment]
according to the latest doc from MDN, firefox does not implement "dblclick" event.
[link from mdn](https://developer.mozilla.org/zh-CN/docs/Web/API/Element/dblclick_event)
